### ISSUE TITLE
Services Refactor

### ISSUE THREAD

**Issue by seanjparker** [hacksoc-manchester/Hackathon_Attendee_Hub#109]
In everything with the exception of the achievements, we are using `getConnnection("...")` provided in typeorm. This restricts our ability to easily refactor the code in the future since we will have many `getConnection("...")` statements scattered throughout the code. Using services and repositories it will mean we only create these repository instances in the controllers where they are needed. Also, it will allow use to easily mock these functions for when we rewrite the tests in the future.

Therefore, we should refactor the code to use the services like in achievements. If it is a remote service (like a database) it will use a typeorm repository using:
`getConnection(...).getRepository(...)` A single service can have many different repositories. E.g. the users will need the hub users and applications users.

**Comment by kzalys** [comment]
I don't completely agree that a single service should be able to have access to multiple repositories. My problem with this approach is that it might lead to a lot of code repetition.

For example: with this approach if you have a model modelA, a model modelB, a service serviceA and serviceA requires access to objects of both modelA and modelB, serviceA would need to implement access methods for modelA AND modelB. If we then needed a service serviceB, we would need to re-implement the same access methods for modelB as we did in serviceA.

I think a better solution would be to make a service for each of the models and have a restriction on services such that one service can access only one repository, the cache and multiple services for objects from other repositories.

You can find an example of my suggested approach in AchievementsProgressService

**Comment by seanjparker** [comment]
I agree with @kzalys that a service can only have access to a single repository.

Also, during the refactoring we will not worry about making services for the applications user and teams since we will be start making our own applications platform.
