### ISSUE TITLE
Admin page- Hardware library management- front-end

### ISSUE THREAD

**Issue by VladM1998** [hacksoc-manchester/Hackathon_Attendee_Hub#59]
We need to have a special admin page for hardware library.
It must have a table with a list of all items and button at the top with a pop-up function to add a new item.
[pages.pdf](https://github.com/hacksoc-manchester/Hackathon_Attendee_Hub/files/2836785/pages.pdf)

**Comment by kzalys** [comment]
Implemented in #76
