### ISSUE TITLE
Some achievements can only be completed by using the QR scanner on the hub

### ISSUE THREAD

**Issue by kzalys** [hacksoc-manchester/Hackathon_Attendee_Hub#66]
Currently the only way for a user to complete automatic achievements is to use our qr scanner on the hub. The reason behind is that the hub expects to receive a POST request with the information about which achievement the user is trying to complete. I made it expect a POST request so that the user would need to use our custom QR scanner which has additional logic to handle such requests with the hope of making it a little bit harder to cheat.
However, it does not seem to be possible to implement a completely reliable QR scanner on the web which would work on all devices. For this reason we should change the system such that the users would be able to interact with the achievements system through 3rd party QR scanners.
The simplest solution would probably be to remove the requirement of receiving the information through a POST request and changing it with a simple GET request which can be sent by any QR scanner.

**Comment by seanjparker** [comment]
When the person clicks on the link to complete the achievement, it will take them to a page (using the GET request). Then if we perform a redirect to the achievement page with a flash message it should be a bit harder for people to cheat since they might not have time to get the link.
