### ISSUE TITLE
Users do net get synchronized between the two databases

### ISSUE THREAD

**Issue by kzalys** [hacksoc-manchester/Hackathon_Attendee_Hub#67]
Currently when the user logs in for the first time, their data is transferred from the applications platform database to the local database of the hub with the hope to improve performance.
The synchronization problems with this approach have proven to outweigh the benefits in performance.
The user system should get changed such that the app uses only the applications platform database for user data.

**Comment by seanjparker** [comment]
Working on this issue on the user-db-sync branch. We now check for an updated password when the password check fails and the user is already on the hub
