### ISSUE TITLE
Achievements system

### ISSUE THREAD

**Issue by andreinonea** [hacksoc-manchester/Hackathon_Attendee_Hub#73]
- [x] Make Achievements class non-abstract
- [x] Hard-code achievements into an array
- [ ] Send a (green?) notification to the user when an achievement is completed
- [ ] Remove isMultiStep field
- [ ] Send GET requests to trigger finishAchievement (for testing)
- [ ] Add field in DB to hold achievement completion state

**Comment by kzalys** [comment]
Just a heads up, for the in-app notifications you just need to attach an object called notification which has fields: message and type (success for green, warning - yellow, danger - red) to the model sent to the EJS template.

So if you'd want to send a green notification for the user you'd write:
`res.render("thePageToRender", { notification: { message: "theMessage", type: "success" }});`

This gets handled by some js code at the bottom of footer.ejs.

You will need to merge in #74 first though as there was a small bug.

**Comment by kzalys** [comment]
Oh and what about the prizes for the achievement? Can't see anything about them in the issue.
